### ISSUE TITLE
New strict comparison operators needed: === and !==

### ISSUE THREAD

**Issue by williamthome** [zotonic/template_compiler#38]
There is a bug in the `template_compiler_operators` module.
Try this in the command line:

```console
template_compiler_operators:eq(1, true, z_template_compiler_runtime, z:c(site)).
```

or 

```console
template_compiler_operators:eq("a", true, z_template_compiler_runtime, z:c(site)).
```

Both will return true.

In `template_compiler_operators:to_values/4` some guards are `is_type(A) orelse is_type(B)`, I think it needs to be always `is_type(A) andalso is_type(B)`.

This is an issue for me because I need to compare term() and boolean() in my template, e.g.: `{% if 30 == true %}`.

Thoughts?

**Comment by mworrell** [comment]
Reading the code this is as designed.

If one of the arguments is a boolean then the other argument is converted to a boolean.  This conversion is loosely and not strict. That means that all values not like `false`, `"false"`, 0 (etc.) are assumed to be `true`.

The integer 30 is non-zero so converted to true.

We always try type conversion before applying the operator.

Looks like you need a more strict or very strict comparison operator. What is the expected outcome of the above three examples?

**Comment by williamthome** [comment]
Oh, I see. This makes sense to me.

I will then propose two new operators, the `===` and `!==`, and two new functions called `seq` and `sne`, a more strict version, like Javascript. These operators will not convert any value, they only will compare the values, e.g.:
- {% if 1 === true %} is false
- {% if 1 !== true %} is true

How about?

**Comment by mworrell** [comment]
Sound good, I also lik te names.

**Comment by mworrell** [comment]
@williamthome See https://github.com/zotonic/template_compiler/pull/39

I wonder if we need to use the `=:=` and `=/=` operator on the Erlang site as well. Currently I use `==` and `/=`.

https://www.erlang.org/doc/reference_manual/expressions.html#term-comparisons

> When comparing an integer to a float, the term with the lesser precision is converted into the type of the other term, unless the operator is one of =:= or =/=. A float is more precise than an integer until all significant figures of the float are to the left of the decimal point. This happens when the float is larger/smaller than +/-9007199254740992.0. The conversion strategy is changed depending on the size of the float because otherwise comparison of large floats and integers would lose their transitivity.

**Comment by williamthome** [comment]
In this case I think it can be even more strict using `=:=` and `=/=`, because e.g. `"A" == [65.0]` is true and `"A" =:= [65.0]` is false. AFAIK `==` and `=:=` is only used to compare int and float.

**Comment by mworrell** [comment]
On the other hand, in JS `5 === 5.0` returns `true`.  In Erlang `5 =:= 5.0` returns `false`.

This is of course because JS doesn't have any real integers but just floating point values.

In the templates `"A"` would be the erlang term `<<"A">>`, so the question might be what the result of `[65] === [65.0]` should be. In JS it is per-definition false, as it will compare two different lists.

Maybe we need to handle comparison of two numbers differently from other values?

**Comment by williamthome** [comment]
Good point.

To compare strings, the filter `to_binary` can be used to be more strict, then `<<"A">> == [65.0]` results in a false value.
I think using a less strict comparator for int and float is also ok because 1 is 1.0, but 1 isn't 1.01.
So `==` and `/=` is the best IMO.

**Comment by mworrell** [comment]
Ok, then I'll await the review from @mmzeeman and then we can merge

**Comment by williamthome** [comment]
Ok, thanks for looking at this, @mworrell! :smiley:
